# Generated by Django 4.2.16 on 2024-11-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='correos_contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('telephone', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
