# Generated by Django 4.2.16 on 2024-11-07 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='correos_contacto',
            new_name='contacto',
        ),
    ]
