# Generated by Django 4.2.16 on 2024-11-07 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_rename_correos_contacto_contacto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='telephone',
            new_name='telephono',
        ),
    ]
